services:
  onlyoffice-documentserver:
    build:
      context: .
    container_name: ooffice-ds
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=172.17.0.1
      - DB_TYPE=postgres
      - DB_HOST=oof-psql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - JWT_SECRET=${JWT_SECRET}  # Replace with a strong secret
      - TZ=Asia/Jakarta # Set timezone to Indonesia (+7)
      - WOPI_ENABLED=true
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - 81:80
      - 443:443
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
      - ./oof/logs:/var/log/onlyoffice/documentserver
      - ./oof/data:/var/www/onlyoffice/Data
      - ./oof/lib:/var/lib/onlyoffice
      - ./oof/rabbitmq:/var/lib/rabbitmq
      - ./oof/redis:/var/lib/redis
      - ./oof/db:/var/lib/postgresql
      # - ./oof/www:/var/www/onlyoffice
       
  onlyoffice-rabbitmq:
    container_name: oof-rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  onlyoffice-postgresql:
    container_name: oof-psql
    image: postgres:12
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./pg-data/:/var/lib/postgresql
